name: Publish Extensions
on:
  push:
    branches: [ main ]

jobs:
  java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install VSCE
        run: npm install -g vsce

      - name: Publish Java
        if: always()
        run: |
          cd java
          vsce package
          vsce publish -p ${{ secrets.VSCE_TOKEN }}

      - name: Publish Theme
        if: always()
        run: |
          cd theme/
          vsce package
          vsce publish -p ${{ secrets.VSCE_TOKEN }}


  # theme:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - run: |
  #         npm install
  #         cd theme
  #     - uses: lannonbr/vsce-action@master
  #       with:
  #         args: "publish -p $VSCE_TOKEN"
  #       env:
  #         VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}