name: Publish Extensions
on:
  push:
    branches: [ main ]

jobs:
  package-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install VSCE
        run: npm install -g @vscode/vsce

      - name: Publish Java Extension Pack
        continue-on-error: true
        run: |
          cd java
          vsce package
          vsce publish -p ${{ secrets.VSCE_TOKEN }}

      - name: Publish Theme Extension Pack
        continue-on-error: true
        run: |
          cd theme/
          vsce package
          vsce publish -p ${{ secrets.VSCE_TOKEN }}

      - name: Publish Dark Theme Extension Pack
        continue-on-error: true
        run: |
          cd theme-dark/
          vsce package
          vsce publish -p ${{ secrets.VSCE_TOKEN }}

      - name: Publish Commons Extensions Extension Pack
        continue-on-error: true
        run: |
          cd commons/
          vsce package
          vsce publish -p ${{ secrets.VSCE_TOKEN }}

      - name: Publish Clojure Extension Pack
        continue-on-error: true
        run: |
          cd clojure/
          vsce package
          vsce publish -p ${{ secrets.VSCE_TOKEN }}

      - name: Publish Github Light Theme
        continue-on-error: true
        run: |
          cd github-light-hight-contrast-theme/
          vsce package
          vsce publish -p ${{ secrets.VSCE_TOKEN }}