name: Publish Extensions
on:
  push:
    branches: [ main ]

jobs:
  java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd java
          npm install
      - uses: lannonbr/vsce-action@master
      - run: cd java
        with:
          args: "publish -p $VSCE_TOKEN"
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}

  # theme:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - run: |
  #         npm install
  #         cd theme
  #     - uses: lannonbr/vsce-action@master
  #       with:
  #         args: "publish -p $VSCE_TOKEN"
  #       env:
  #         VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}