name: Publish Extensions
on:
  push:
    branches: [ main ]

jobs:
  java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install VSCE
        run: npm install -g vsce

      - name: Publish Java Extension Pack
        continue-on-error: true
        run: |
          cd java
          vsce package
          vsce publish -p ${{ secrets.VSCE_TOKEN }}

      - name: Publish Theme Extension Pack
        continue-on-error: true
        run: |
          cd theme/
          vsce package
          vsce publish -p ${{ secrets.VSCE_TOKEN }}

      - name: Publish Github Light Theme
        continue-on-error: true
        run: |
          cd github-light-hight-contrast-theme/
          vsce package
          vsce publish -p ${{ secrets.VSCE_TOKEN }}